name: Build and Deploy
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: Pmp-Solutions/PmpTeamMate-docs@master
      env:
        ACCESS_TOKEN: b2712a1e59af8f32dc54019a9801e36094e6e409
        BUILD_DIR: docs/.vuepress/dist/ # The folder, the action should deploy.
        BUILD_SCRIPT: yarn && vuepress build docs # The build script the action should run prior to deploying.